version: '2'
services:
    ubuntu-build:
        image: ${COMPOSE_IMAGE}
        volumes:
            - ../../:/code
            - ${DEST}:/dest
            - ./compose-entrypoint:/compose-entrypoint

        command: /compose-entrypoint

        environment:
            - CMAKE_BUILD_TYPE
            - CPACK_GENERATOR
            - PACKAGE_VERSION_SUFFIX
            - PACKAGE_NAME_SUFFIX
            - CMAKE_EXTRA_OPTIONS
            - MAKE_OPTS

